### ISSUE TITLE
[CRITICAL] Rendering SLS 'base:zabbix.agent' failed: found unexpected ':'

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/zabbix-formula#107]
Hi

I'm getting the following error. Any idea what's going on ? 

> [CRITICAL] Rendering SLS 'base:zabbix.agent' failed: found unexpected ':'

Here is my pillar. It looks ok to me. 

```
zabbix:
  lookup:
    version_repo: '4.0'
    agent:
      version: '4.0'

zabbix-agent:
  server: '10.3.0.214'
  serveractive: '10.3.0.214'
{% if grains['virtual'] == 'LXC' or grains['virtual'] == 'lxc' %}
  hostmetadata: lxc
{% endif %}
  pidfile: /var/run/zabbix/zabbix_agentd.pid
  logfile: /var/log/zabbix/zabbix_agentd.log
  logfilesize: 0
```
