### ISSUE TITLE
Fix `salt-lint` violations => implement `semantic-release` inc. CI

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/zabbix-formula#129]
Having an initial look at what would be required to get `semantic-release` running for this formula.  The whole package involves introducing multiple linters to check the code during the Travis run.  The current codebase (at 96b653d) has a large number of `salt-lint` violations:

* https://travis-ci.org/myii/zabbix-formula/jobs/596261955#L258-L488

Even if `semantic-release` takes a while to be introduced to this formula, these violations really need to be resolved.

**Comment by myii** [comment]
@hatifnatt @xenadmin Actually, this formula is in pretty ripe for conversion.  Setting `4.4` for installation, we've got a nice set of passes already:

* https://travis-ci.org/myii/zabbix-formula/builds/596282536

That's based on the formula-specific `state_top` as suggested in the `README`, i.e.:

```yaml
      state_top:
        base:
          '*':
            - zabbix.agent.repo
            - zabbix.agent.conf
            - zabbix.server.repo
            - zabbix.server.conf
            - zabbix.frontend.repo
            - zabbix.frontend.conf
```

If you're OK with the tabs being changed to spaces, we could have this rolled out pretty soon.
