### ISSUE TITLE
[BUG] version_repo override ignored on windows?

### ISSUE THREAD

**Issue by viq** [saltstack-formulas/zabbix-formula#144]
### Formula commit hash / release tag
497406a77a3431d2e708e2eeadca9221a1833ebf

### Versions reports (master & minion)
Master:
```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: 0.27.7
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: 0.27.4
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```
Minion:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 
```

### Pillar / config used

`salt minion pillar.item zabbix zabbix-agent`
```
minion:
    ----------
    zabbix:
        ----------
        lookup:
            ----------
            agent:
                ----------
                version:
                    5.0.2.2400
        psk:
            ----------
            identity:
                psk001
            value:
                0xdeadbeef
        version_repo:
            5.0
    zabbix-agent:
        ----------
        server:
            - zabbix.server
        tlsaccept:
            psk
        tlsconnect:
            psk
        tlspskfile:
            C:\\Program Files\\Zabbix Agent\\zabbix_agentd.psk
        tlspskidentity:
            psk001
```

---

### Describe the bug

https://github.com/saltstack-formulas/zabbix-formula/blob/master/zabbix/files/default/etc/zabbix/zabbix_agentd.conf.jinja#L19 checks for `zabbix.version_repo`. `salt minion config.get zabbix:version_repo` returns `5.0`. Despite that, putting `# TEST zabbix.version_repo {{ zabbix.version_repo }}` above that line returns `# TEST zabbix.version_repo 2.2` and the `if` (and all like it) evaluate to `False`

### Steps to reproduce the bug

Try to enable TLS config on a Windows minion.

### Expected behaviour

New zabbix agent version installed and recognized, with proper configuration options enabled.

### Attempts to fix the bug

So far I "cheated", and placed a modified version of https://github.com/saltstack-formulas/zabbix-formula/blob/master/zabbix/defaults.yaml with `version_repo` set to `5.0`
