### ISSUE TITLE
if you dont have a user shell specified, this formula fails to run on FreeBSD

### ISSUE THREAD

**Issue by stuartgh** [saltstack-formulas/zabbix-formula#72]
Problem:
=======
I had a simple config running on a FreeBSD server:
```
zabbix-agent:
  server:
    - <serveraddr>
  serveractive:
    - <serveraddr>
  listenip: 0.0.0.0
  listenport: 10050
  logfile: /var/log/zabbix/zabbix_agentd.log
  userparameters:
    - net.ping[*],/usr/bin/fping -q -c3 $1 2>&1 | sed 's,.*/\([0-9.]*\)/.*,\1,'
  hostname: {{ grains['fqdn'] }}
```

But recently I am getting the following error whenever I run salt:
```
    Data failed to compile:
----------
    Rendering SLS 'base:zabbix.users' failed: Jinja variable 'dict object' has no attribute 'shell'
ERROR: Minions returned with non-zero exit code
```

Looking at the default map.jina it looks as though someone did not update the FreeBSD section with a default shell.
