### ISSUE TITLE
Merge failing for repo

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/zabbix-formula#74]
Hi

The merge function in map.jinja doesn't seem to work in my Ubuntu installation. 
`}, merge=salt['pillar.get']('zabbix:lookup')) %}`

My minion sees the following but it still attemts to install version 2.2. I have done a pull. Any ideas? 

```
local:
    ----------
    agent:
        ----------
        version:
            3.4
        version_repo:
            3.4
```

**Comment by fredprod** [comment]
Hi, what do you have in your pillar? I think you must have something like:
```
zabbix:
  lookup:
    version_repo: 3.4
```

**Comment by waynegemmell** [comment]
It looks like this. 

```
zabbix:
  lookup:
    agent:
      version: 3.2
      version_repo: 3.2

zabbix-agent:
  server:
    - 10.3.0.214
  serveractive:
    - 10.3.0.214
```

**Comment by fredprod** [comment]
Perhaps an issue with pillar.example.
version_repo seems to be declared only under zabbix.lookup.
Can you check which repository you have in apt sources list?

**Comment by waynegemmell** [comment]
deb http://repo.zabbix.com/zabbix/2.2/ubuntu xenial main

**Comment by waynegemmell** [comment]
Ok, I changed my pillar as follows
```
zabbix:
  lookup:
    version_repo: '3.4'
    agent:
      version: '3.4'
```
It works! Only after removing the old file but at least it works. 

Thanks for the help
